# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5822d8a29b2c9acc036a79b73413376c2b0f9cf6910a4a88a6acc4de8df876203e8dbb3f720e345a18e5b5299bfd48bae4963ea9f2da1c3fb0584351a993a75d

test:
  secret_key_base: c92a98174e26152c5c36998c9c288567099f3854eb32b3b5d6230b2d84286f68a1f1ca8f4a18f38690662548231461f54f1d9b8f98106ebe5e3874d0de586173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
